languageCode = "en"
languageName = "English"
weight = 1
title = "Richmond Web"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo_with_text_alt.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Personal website of Riccardo Cannistrà"
  copyright = "&copy; { year } Riccardo Cannistrà"

[params.author]
  name = "Riccardo Cannistrà"
  image = "img/author.jpg"
  headline = "Software Engineer on a journey to become 1% better every day. 🚀"
  bio = "Copenhagen-based Software Engineer by day, bedroom DJ by night, and a curious explorer whenever I break free from the keyboard. On this blog, I share stories from my experiences, travels, hobbies, and passions. If you enjoy the content, feel free to connect!"
  links = [
    { email = "mailto:rickystream94@gmail.com" },
    { link = "https://richmondweb.it/" },
    { linkedin = "https://linkedin.com/in/riccardo-cannistra" },
    { youtube = "https://www.youtube.com/@rickystream94" },
    { github = "https://github.com/rickystream94" },
    { facebook = "https://facebook.com/riccardo.cannistra17" },
    { instagram = "https://instagram.com/xrichmondx94" },
    { x-twitter = "https://twitter.com/rickystream94" },
    { microsoft = "https://account.xbox.com/en-US/profile?gamertag=XxRichmond94xX" },
    { steam = "https://steamcommunity.com/id/rickystream94/" }
  ]
